spring.application.name=TeamTrack
security.jwt.secret=VGhpc0lzQVNlY3VyZUFuZExvbmdFbm91Z2hLZXlGb3JKV1RIUzI1Ng==
security.jwt.expiration-ms=86400000


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
# For automatic table creation
spring.jpa.hibernate.ddl-auto=update
