spring.application.name=TeamTrack
security.jwt.secret=VGhpc0lzQVNlY3VyZUFuZExvbmdFbm91Z2hLZXlGb3JKV1RIUzI1Ng==
security.jwt.expiration-ms=86400000


#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.datasource.url=jdbc:postgresql://db.kyqoakmofonjghkiejhv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Shivam@Singh


spring.datasource.driver-class-name=org.postgresql.Driver
# For automatic table creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
