spring.application.name=TeamTrack
security.jwt.secret=VGhpc0lzQVNlY3VyZUFuZExvbmdFbm91Z2hLZXlGb3JKV1RIUzI1Ng==
security.jwt.expiration-ms=86400000


#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


#spring.datasource.url=jdbc:postgresql://db.kyqoakmofonjghkiejhv.supabase.co:5432/postgres
#spring.datasource.url=jdbc:postgresql://db.kyqoakmofonjghkiejhv.supabase.co:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=Shivam9797341381

spring.datasource.url=jdbc:postgresql://ep-noisy-morning-am2i6kbt-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mpPDXosjd01S

spring.datasource.driver-class-name=org.postgresql.Driver
# For automatic table creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
